### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-obtrusive-livetest#65]
especially https://github.com/franzenzenhofer/f19n-livetest-chrome-extension/tree/master/sample-rules

**Comment by neuling** [comment]
did some updates to the readme. can you check if you miss anything:

https://github.com/franzenzenhofer/f19n-livetest-chrome-extension/commit/531566b64420615710f590476c4de12085cd56cc#diff-8f05ec84a329e38f5745e82736913c6a
