### ISSUE TITLE
Hide the app as standard behaviour

### ISSUE THREAD

**Issue by Cryt1c** [franzenzenhofer/f19n-obtrusive-livetest#71]
Hi,

awesome tool! Thanks a lot! Helps me a ton. But not always.. :) I would like to have the app hidden as standard behaviour. Is there already a config for that, which I am missing? It keeps being opened every time i open a new site.

Cheers!

**Comment by genmacg** [comment]
I would also highly appreciate being able to adjust this behaviour via config.

**Comment by franzenzenhofer** [comment]
hi, thx, i wrote a spec and we will prop. implement it soon 
https://github.com/franzenzenhofer/f19n-obtrusive-livetest/issues/72

**Comment by franzenzenhofer** [comment]
hi, if you like you can check out this branch: 

https://github.com/franzenzenhofer/f19n-obtrusive-livetest/tree/enhanced-configuration

where we try to make the show/not-show/execute tests/notexecute testes/ more configurable

**Comment by franzenzenhofer** [comment]
feedback welcome

**Comment by franzenzenhofer** [comment]
it's now configurable in the new app version 0.0.6. 
https://chrome.google.com/webstore/detail/f19n-obtrusive-live-test/jbnaibigcohjfefpfocphcjeliohhold
