### ISSUE TITLE
new easier whitelist/blacklist management (run/don't run logic)

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-obtrusive-livetest#72]
# site wide setting:

in the settings above the whitelist / blacklist

![image](https://user-images.githubusercontent.com/323190/31585568-4ea4718c-b1c4-11e7-8042-5e0c8df924a0.png)

ad a (radio button) setting:

(x) run on every page ( ) only run on whitelisted pages

clicking on “run on every page” ads
`*://*`
to the whitelist - at the start of the list
(and removed if exists  an` !*://* `entry)

choosing the other option, removes
`*://*`
and adds
`!*://*`
to the whitelist / blacklist. (at the start of the list)

note: the setting should be remember over browser restarts and app updates

———————————————————

# case: livetest is active (visible)

if livetest is active on page show the icon in color
![image](https://user-images.githubusercontent.com/323190/31585574-5f2ffe36-b1c4-11e7-9ac6-ac633f1c9778.png)

1)

![image](https://user-images.githubusercontent.com/323190/31585578-713187ee-b1c4-11e7-8943-b85504edd0be.png)

- click on X 
- hides livetest window
- disables livetest in this tab
- 

2) 

![image](https://user-images.githubusercontent.com/323190/31585580-793d7ee8-b1c4-11e7-9613-a17df192a87f.png)

click on Icon (which is displayed in color)

shows dialog (similar like ) ublock 

![image](https://user-images.githubusercontent.com/323190/31585586-81514466-b1c4-11e7-9785-abf66e5c05c0.png)

with following options:

>>>

```
Never run tests on

www.example.com/* 
*.example.com/*
this page.

Don’t run in the current tab.

Settings
```

>>>>
![image](https://user-images.githubusercontent.com/323190/31585603-c32b86f8-b1c4-11e7-9c52-2c55a3575163.png)

(note: clickable elements should be blue and underlined)

click on
> www.example.com/*
(of course substituted on the page with the subdomain, domain you are currently on)

- hides livetest window
- adds `!*://www.example.com/* `to the whitelist/blacklist (if non exists yet)
- if an entry `*://www.example.com/* `exists in the whitelist/blacklist this entry is removed
- reloads the page (with the tests now does not run on this page)
- 

————————-

click on
`> *.example.com/*`
(of course substituted on the page with the domain you are currently on)

- hides livetest window
- adds `!*://*.example.com/* `to the whitelist/blacklist (if non exists yet)
- if an entry `*://*.example.com/*` exists in the whitelist/blacklist this entry is removed
- reloads the page (with the tests now does not run on this page)

——————————

click on 
> this page

- hides livetest window
- adds a blacklist entry for this URL (without parameters)
- (if a whitelist entry for this URL (without parameters) does exist, remove it)
- reloads the page (with the tests now not running on this page)
- 

—————————————

click on
>Don’t run in the current tab.

- Same behavior like a click on [x] in the livetest window.
- Hide config window.
-----------------------------------

Click on "Settings" leads to the settings page.

—————————
# case livetest is not active 

![image](https://user-images.githubusercontent.com/323190/31585597-a417b03e-b1c4-11e7-9e6f-6395165b131c.png)

icon is displayed in gray

————

if the tests were not running, just because the tests were disabled in this tab (because of a previous click on the X in the livetest window) or a click on “Don’t run in the current tab.”

- enable livetests in this window
- the page gets reloaded
- with the tests now running

——————————

if the tests were not running, because of a blacklist entry 

Display following dialogue

>>>

```
Always run tests on

www.example.com/* 
*.example.com/*
this page.

Settings
```

>>>>

————————-
![image](https://user-images.githubusercontent.com/323190/31585600-b8642978-b1c4-11e7-9051-f475a9ef7a4d.png)

click on
`> www.example.com/*`
(of course substituted on the page with the subdomain, domain you are currently on)

- adds `*://www.example.com/`* to the whitelist/blacklist (if non exists yet)
- if an entry` !*://www.example.com/*` exists in the whitelist/blacklist this entry is removed
- reloads the page (with the tests now run on this page)

———————-
click on
`> *.example.com/*`
(of course substituted on the page with the protocoll, subdomain, domains you are currently on)

- adds `*://*.example.com/* `to the whitelist/blacklist (if non exists yet)
- if an entry` !*://*.example.com/*` exists in the whitelist/blacklist this entry is removed
- reloads the page (with the tests now run on this page)

click on
> this page.
(of course substituted on the page with the protocoll, subdomain, domains you are currently on)

- adds an enabling entry to the whitelist - of this URL - without any parameters
- if an disabling entry is in the whitelist/blacklist - of this URL wihtout any paramters - the entry is removed
- reloads the page (with the tests now run on this page)

——————————-

Click on "Settings" leads to the settings page.

-------------------

the whitelist/blacklist entry should prevail with app updates and browser re-starts.

**Comment by franzenzenhofer** [comment]
added "Settings" option in the overlay.

**Comment by franzenzenhofer** [comment]
case http://www.karriere.at/

i.e.: https://www.karriere.at/jobs/4960296

IS:
```
Never run tests on
www.karriere.at/*
*.www.karriere.at/*
*.karriere.at/*
this page
```


SHOULD:
```
Never run tests on
www.karriere.at/*
*.karriere.at/*
this page
```

>*.www.karriere.at/*
doesn't make sense

click on:
```
www.karriere.at/* -> this blacklist entry -> !https://www.karriere.at* (OK)
*.www.karriere.at/* -> this blacklist entry -> !https://*.karriere.at* (OK, but wrong link text, should be *.karriere.at/*)
*.karriere.at/* -> this blacklist entry -> !https://*..at* (NOT OK, should not exit )
this page -> blacklist enttry -> !https://www.karriere.at/jobs/4960296 (OK)
```
same partly wrong behavior with the whitelist function if page was disabled

**Comment by neuling** [comment]
@franzenzenhofer thanks. should both be fixed now.

**Comment by franzenzenhofer** [comment]
So far so good, testing more pages right now

the "site wide feature" is still open (see original spec)

![image](https://user-images.githubusercontent.com/323190/31820368-4dd2395c-b5a1-11e7-803f-aaaab957d2f3.png)

**Comment by neuling** [comment]
True. What should happen when i click on "run on every page" but already have existing entries in my list? Delete everthing? Insert "*://*" on top of the list? Same question for "only run on whitelisted pages".

**Comment by franzenzenhofer** [comment]
IS: blacklist entry is domain sensitive

i.e.: on https://www.karriere.at/jobs/4960296

in the overlay click on
```
www.karriere.at/* -> leads to this blacklist entry -> !https://www.karriere.at*
*.karriere.at/* ->  leads to this blacklist entry -> !https://*.karriere.at*
```

SHOULD: blacklist entry is domain insensitive

```
www.karriere.at/* -> leads to this blacklist entry -> !*://www.karriere.at*
*.karriere.at/* ->  leads to this blacklist entry -> !*://*.karriere.at*
```

note, this must also be considered in the blacklist entry / remove logic

reasoning: i believe the treat http/https as one is in the majority of the time the desired behaviour.
if they want to treat protocols differently then they have to go into the blacklist manually

**Comment by franzenzenhofer** [comment]
good point, but I only want to manage the default behaviour

the default behaviour is that the first entry is 

`*://*`

this setting just switches the default behaviour, so that the first entry is

`!*://*`

this setting does not touches the rest of the rules, just either

changes the first line (if `*://*` or `!*://*` is present)

or ads 
`!*://*` or `*://*`
if there is something else in the first line.

but yeah, the wording should be that is just deals with default behaviour

`Default behavior: (x) run on every page ( ) only run on whitelisted pages`

(not, the active button is set based on existance of `!*://*` or `*://*` in the first line, if none, then none of these buttons should be selected)

of course I'm very open for a better solution / wording

**Comment by franzenzenhofer** [comment]
@neuling big question, would a "Reset Whitelist/Blacklist to Default" Button (and functionality) be feasible. if browsing around I see that is is indeed easy to get a huge and slightly screwed up whitelist/blacklist. so a "factory reset" would be awesome

**Comment by neuling** [comment]
@franzenzenhofer disable, enable or custom configuration + reset configuration is now implemented.

![8whrvny7ig](https://user-images.githubusercontent.com/238180/31895477-90810180-b811-11e7-9771-76b9074b3a88.gif)

disabled internally maps to "*://*", disabled to "!*://*" and custom configuration will use the list below.

two things i am not sure about if its correct implemented.

1) i would say it makes sense to disable/hide the custom configuration (black/whitelist) in some way when "run on every site" or "disabled" is selected since changes will have no effect.

2) if "disabled" or "run on ever site" is selected and you open the popup and add a custom rule, the mode will automatically switch to "custom configuration" and the site will be added or removed.

pls test the current implementation and give some feedback. thanks.

**Comment by franzenzenhofer** [comment]
hi @neuling 

sadly not what I want and need, that is why I strongly prefer written spec discussions.

- I do not want to manage total behavior. (no enable on all sites, no kill switch to overall disable)
- I want to manage default behavior. (with a simple setting)

what I need:

![image](https://user-images.githubusercontent.com/323190/31901900-3b4b597e-b823-11e7-98c6-163e4edd23ab.png)

Please add the Options: 

`Default behaviour: () Run on every page (default enable) () Only run on enabled pages (default disable)
`

Default is 
1 `() Run on every page (default enable)`
selecting this 

looks into the blacklist for any exact match of
`!*://*`
and deletes all these entry
and adds
`*://*`
as the first entry

The other option is 


The other option is 
1 `() Only run on enabled pages (default disable))`
selecting this 

looks into the blacklist for any exact match of
`*://*`
and deletes all these entries
and adds
`!*://*`
as the first entry

-----------
the setting looks into the first line of this blacklist/whitelist to determine if the the radio button is set to 1 or 2
-----------

please enable this behavior
I will later rework the interface to name the total behavior differently as I do not want to cover it prominently

**Comment by neuling** [comment]
@franzenzenhofer done. pls re-test.

**Comment by neuling** [comment]
![u52tk7uoui](https://user-images.githubusercontent.com/238180/31937893-2549de82-b8b6-11e7-9593-111bca13b804.gif)

**Comment by franzenzenhofer** [comment]
hi moritz
somtimes it crashes... and the old location get stuck
![image](https://user-images.githubusercontent.com/323190/31963129-ff140266-b8ff-11e7-9563-a15f6166d02d.png)
any idea? turning it (the browser) on and off again seems to work. hard to replicate

**Comment by neuling** [comment]
ah, thanks. got it. it happens if you have two (or more) browser windows open. should be fixed by this commit: https://github.com/franzenzenhofer/f19n-obtrusive-livetest/commit/5d3f4f2a78ce1e8d6ef0b47655d0d05054fccbe7

**Comment by franzenzenhofer** [comment]
looks very good and just works #done
