### ISSUE TITLE
upadate and fix security notifications

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-obtrusive-livetest#79]
update react & stuff

fixe security critical dependencies, see 

https://github.com/franzenzenhofer/f19n-obtrusive-livetest/network/alerts

**Comment by neuling** [comment]
@franzenzenhofer Can you please checkout the branch https://github.com/franzenzenhofer/f19n-obtrusive-livetest/tree/feature/update-and-fix-security-nofitications-gh79 and run a clean build for the extension.

It's probably a good idea to remove the whole `node_modules` folder and run `npm install` for a clean set of packages. Then run `grunt` and add the extension to chrome. Test if everything works as expected.

You shouldn't see ANY dependencies warning anymore.

> added 134 packages from 60 contributors, removed 207 packages, updated 915 packages and audited 12147 packages in 14.875s
found 0 vulnerabilities

**Comment by neuling** [comment]
Issue #84 should also be fixed. Also updated the readme. No `chrome-cli` required anymore.

@franzenzenhofer Please check out this branch and test if everything works for you.

**Comment by franzenzenhofer** [comment]
`f19n-obtrusive-livetest fe$ grunt
Loading "sass.js" tasks...ERROR
>> SyntaxError: Unexpected token (

Running "config:dev" (config) task
>> Configure 2 variables for current target.
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.
Awesome-MacBook:f19n-obtrusive-livetest fe$ 
`

**Comment by neuling** [comment]
Just to be sure, did you `rm -rf node_modules` and made a clean install `npm install` before running `grunt`?

What versions of node (`node --version`) and npm (`npm --version`) are you running?

I just opened my old MBP, did a clean checkout + npm install and everything works as expected.

**Comment by franzenzenhofer** [comment]
did  

- git clone https://github.com/franzenzenhofer/f19n-obtrusive-livetest
-  npm install
- grunt

now it works!

**Comment by neuling** [comment]
Ok, you should probably update both your node and npm to newer versions before we spend more time on this issue. I am running node 11.2.0 and npm 6.4.1.

Found some issues from other users complaining about this bug. Newer node version solved it. For example: https://github.com/keeweb/keeweb/issues/1083#issuecomment-452242893

**Comment by franzenzenhofer** [comment]
yeah, updating it did the trick, could build the application

this is the output I get in the console 

![image](https://user-images.githubusercontent.com/323190/53873009-c4a70000-3fff-11e9-8285-da073a7318f3.png)

**Comment by franzenzenhofer** [comment]
@neuling 
bekommen wir das auch noch weg
![image](https://user-images.githubusercontent.com/323190/54202247-e3116d80-44cf-11e9-85d8-9e682662d9be.png)
falls mit überschaubaren aufwand ist dies eine beauftragung

**Comment by neuling** [comment]
Muss ich mir nochmal ansehen. Eigentlich habe ich diese Warnings in folgendem Commit(https://github.com/franzenzenhofer/f19n-obtrusive-livetest/commit/5577469f315ca9b17d279ecab469b0727d9b0b41) behoben.

Checke ich nochmal.

**Comment by neuling** [comment]
Should be fixed. Please pull, `npm install` and try again.
