### ISSUE TITLE
Google Page Speed Api Key Global Variable

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-obtrusive-livetest#81]
on the settings page there should be a section

Globale Variables
 * Google Page Speed Insights Key: [                     ] (input form)
 * Google Mobile Friendly Test Key: [                      ] (input form)
 * Rate Limited Domains: [                          ] (input form)

these global varialbes should be available in the context of the rules as varialbes

**Comment by neuling** [comment]
First implementation is done. Please test if it works for you:

![DLvXELwv](https://user-images.githubusercontent.com/238180/54194260-16e29800-44bc-11e9-89dd-3a2731d0d92d.png)

Config has a new key called `availableGlobalRuleVariables` which controls the available global variable inputs and their names.

You can access the global variables/settings inside a rule via `this.getGlobals()`:

```javascript
const globals = this.getGlobals();
console.log(globals.variables.google_page_speed_insights_key);
```

**Comment by franzenzenhofer** [comment]
works as intended
