### ISSUE TITLE
Priority Sorting 

### ISSUE THREAD

**Issue by franzenzenhofer** [franzenzenhofer/f19n-obtrusive-livetest#82]
when returning a result, it should be possible to submit an option "priority" value (integer)

i.e.: done(that.createResult(lable, msg, type, what, priority));
done(that.createResult(lable, msg, type, what, 10000 )); 

priority default is 0 

when rules are executed and the output listed in the panel. then the current sorting (errors first, then warning, info) should remain.

each section (errors, warning, info) should be sorted then descending (highes first, lowest last) based on priority.

**Comment by neuling** [comment]
Done.

`createResult` now accepts a 5th argument 'priority'.

```javascript
…
return done(this.createResult('TEST', 'High prio message', 'info', null, 10));
…
```

Btw you can always return an object instead of `createResult`. So you don't have to write down all the unnecessary arguments just to add a priority:

```javascript
…
return done({ label: 'Test', message: 'High prio message', priority: 10 });
…
```

Please pull from the master, apply some priorities to your rules and test it.

**Comment by franzenzenhofer** [comment]
added priors to these cases

![image](https://user-images.githubusercontent.com/323190/54120309-ae31e780-43f7-11e9-9133-aaedb5a0b19e.png)

seo title - prio 1000
h1 - prio 900
fb - prio 800

only in cases of an "info" response .

but in the case of
https://www.veganblatt.com/superfood-pralinen
it does not work, no priority sorting applied 

![image](https://user-images.githubusercontent.com/323190/54120470-0f59bb00-43f8-11e9-9ee1-3215ed643635.png)

**Comment by neuling** [comment]
@franzenzenhofer should be fixed. Pls pull and try again.

**Comment by franzenzenhofer** [comment]
works as intended!
