### ISSUE TITLE
Remove chrome.loadTimes() and replace with standardized APIs

### ISSUE THREAD

**Issue by neuling** [franzenzenhofer/f19n-obtrusive-livetest#83]
We should remove `chrome.loadTimes()` since its deprecated and throws extension warnings:

![screenshot 2019-03-01 11 05 49](https://user-images.githubusercontent.com/238180/53631251-6ac6c480-3c12-11e9-8d3c-918b629456c8.png)

What todo:

- [ ] Replace the usage of `loadTimes` in all rules with standardized APIs (https://developers.google.com/web/updates/2017/12/chrome-loadtimes-deprecated)
- [ ] Remove `chrome.loadTimes()` from the core https://github.com/franzenzenhofer/f19n-obtrusive-livetest/blob/f6a9dc0cc65848030a06537224c0c26888634e53/src/javascripts/document_idle.js#L1

**Comment by franzenzenhofer** [comment]
please  (I see this as a nearly realted to security update task, as this will break the application in the future for sure)

**Comment by neuling** [comment]
I removed the deprecated `loadTimes` API from our core. To be downward compatibility for users that might use `getChromeLoadTimes()` in their custom rules, calling this function will throw an error (see screenshot).

![screenshot 2019-03-06 13 34 52](https://user-images.githubusercontent.com/238180/53881966-4ead9380-4015-11e9-9491-48516023ba97.png)

Next step is to fix both of the core rules to use standardized APIs.

**Comment by franzenzenhofer** [comment]
ich kümmer mich drum

**Comment by neuling** [comment]
Ok, ich würde den Branch `update-and-fix-security-notifications-gh79` gerne in den master mergen damit ich die intakte build-pipeline für die restlichen Issues habe. 

Passt das? Du fixt die zwei Rules dann entweder im master oder machst dir einen eigenen Branch dafür.

**Comment by neuling** [comment]
Done!
